services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: cook_book_adminer
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      - postgres

  migrate-auth:
    image: migrate/migrate:latest
    container_name: cook_book_migrate_auth
    volumes:
      - ./auth/migrations:/migrations
    command: [ "-path", "/migrations", "-database", "${DATABASE_URL}", "up" ]
    depends_on:
      postgres:
        condition: service_healthy
  auth-service:
    build: ./auth
    container_name: cook_book_auth_service
    ports:
      - "${AUTH_SERVICE_PORT}:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      AUTH_SERVICE_PORT: 8000
    depends_on:
      postgres:
        condition: service_healthy
      migrate-auth:
        condition: service_completed_successfully

  # migrate-recipe:
  #   image: python:3.12-slim
  #   container_name: cook_book_migrate_recipe
  #   volumes:
  #     - ./recipe:/app
  #   working_dir: /app
  #   command: ["sh", "-c", "pip install alembic psycopg2-binary && alembic upgrade head"]
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     migrate-auth:
  #       condition: service_completed_successfully

  # recipe-service:
  #   build: ./recipe
  #   container_name: cook_book_recipe_service
  #   ports:
  #     - "${RECIPE_SERVICE_PORT}:8080"
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #     JWT_SECRET: ${JWT_SECRET}
  #     RECIPE_SERVICE_PORT: 8080
  #     UPLOAD_DIR: /app/static/uploads
  #   volumes:
  #     - uploads_volume:/app/static/uploads
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     migrate-recipe:
  #       condition: service_completed_successfully

volumes:
  postgres_data:
  uploads_volume:
