@startuml сиквенс_диаграмма_регистрация_и_вход
!theme mars

skinparam actor {
  FontStyle bold
  BackgroundColor #FFB6C1
}
skinparam participant {
  FontColor black
  FontStyle bold
}
skinparam database {
  FontStyle bold
  BackgroundColor #ADD8E6
}
skinparam backgroundcolor #F5F5DC
skinparam roundcorner 18
skinparam actorStyle hollow

actor "Юзер" as User #pink
participant "Frontend\n(Vue)" as Frontend #FFE4B5
participant "Auth Service\n(Go)" as Auth #B0E0E6
database "PostgreSQL" as DB #ADD8E6

User ++ #pink
User -> Frontend ++ #FFE4B5 : Заполняет email/пароль,\nнажимает "Регистрация"
Frontend -> Auth --++ #B0E0E6 : POST /auth/register\n{email, password}
Auth -> DB --++ #ADD8E6 : Проверить email
DB --> Auth --++ #B0E0E6 : ok / exists
Auth -> DB --++ #ADD8E6 : INSERT users (bcrypt hash)
DB --> Auth --++ #B0E0E6 : user_id
Auth --> Frontend --++ #FFE4B5 : 201 Created
Frontend --> User : Уведомление,\nпереход к форме входа

User -> Frontend : Вводит email/пароль,\nнажимает "Войти"
Frontend -> Auth --++ #B0E0E6 : POST /auth/login
Auth -> DB --++ #ADD8E6 : SELECT hashed_password
DB --> Auth --++ #B0E0E6 : hash
Auth -> Auth : bcrypt.verify()
Auth --> Frontend --++ #FFE4B5 : 200 OK\n(Set-Cookie: tokens)
Frontend -> Frontend : Сохранить токены в куки
Frontend --> User : Редирект на главную (/)

@enduml